SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION test1(A IN money.id%TYPE, B OUT money.id%TYPE)
RETURN number
IS

BEGIN
	DBMS_OUTPUT.PUT_LINE(A);
	B := 10;
	return A+10;
END test1;
/

DECLARE
	NUM number;
	NUMb number;
BEGIN
	NUM := test1(2, NUMB);
	DBMS_OUTPUT.PUT_LINE(NUM);
	DBMS_OUTPUT.PUT_LINE(NUMB);
END;
/